name: Publish ESLint Plugin

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org/

            - name: Authenticate to npm
              run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - run: pnpm install
              name: Install dependencies

            - name: Build
              run: pnpm build

            - name: Lint & Type Check
              run: pnpm validate

            - name: Publish
              run: npm publish --access public
